{{ range $configmap_name, $configmap := .Values.configmap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl $configmap_name $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "pewty.labels" $ | nindent 4 }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- tpl (toYaml $configmap) $ | nindent 2 }}
{{- end }}
