{{- if eq .Values.controller "daemonset" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "pewty.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pewty.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "pewty.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pewty.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.configmap }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.secret }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccount: {{ include "pewty.fullname" . }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.pod.container }}
      containers:
      {{- range $container_name, $container := .Values.pod.container }}
        - name: {{ $container_name }}
          {{- if $.Values.image.pullPolicy }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- end }}
          {{- toYaml $container| nindent 10}}
      {{- end }}
      {{- end }}
      {{- if .Values.pod.initContainer }}
      initContainers:
      {{- range $container_name, $container := .Values.pod.initContainer }}
        - name: {{ $container_name }}
          {{- if $.Values.image.pullPolicy }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- end }}
          {{- toYaml $container| nindent 10}}
      {{- end }}
      {{- end }}
      {{- if .Values.pod.volume }}
      volumes:
      {{- range $volume_name, $volume := .Values.pod.volume }}
        - name: {{ $volume_name }}
          {{- tpl ( $volume | toYaml ) $ | nindent 10}}
      {{- end }}
      {{- end }}
{{- end }}
