{{ range $secret_name, $secret := .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "pewty.labels" $ | nindent 4 }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- with $secret }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
