{{ range $service_name, $service := .Values.serviceMonitor }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ tpl $service_name $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "pewty.labels" $ | nindent 4 }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "pewty.selectorLabels" $ | nindent 6 }}
  {{- with $service.endpoints }}
  endpoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
