{{- range $release := .Values.releases }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $release.name }}
  namespace: {{ $release.namespace }}
spec:
  install:
    createNamespace: false
  chart:
    spec:
      chart: {{ $release.dir }}
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: {{ $release.source }}
        namespace: cd
      valuesFiles:
      {{- tpl $release.valuesFiles $ | toYaml | nindent 6 }}
      version: '*'
  interval: 1m0s
  {{- with $release.values }}
  values:  
    {{- tpl $release.values $  | nindent 4}}
  {{- end }}
{{- end }}
